# =======================
# Server
# =======================
server.port=${PORT:8118}
spring.application.name=car-rental-backend

# =======================
# PostgreSQL (Supabase Session Pooler)
# =======================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dqmwrrayymghyyzjqgwc
spring.datasource.password=phani143
spring.datasource.driver-class-name=org.postgresql.Driver

# =======================
# JPA / Hibernate
# =======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =======================
# Hikari
# =======================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2


# =======================
# File Upload Config
# =======================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# =======================
# Payment (Razorpay)
# =======================
razorpay.key_id=rzp_test_RYsjZGpaSI78sz
razorpay.key_secret=KAnZ0bEa9Ge1MGGmqfPgpTQ4
